apiVersion: v1
kind: Service
metadata:
  name: question-service-db
  labels:
    app: question-service-db
spec:
  selector:
    app: question-service-db
  ports:
  - protocol: "TCP"
    port: 9001
    targetPort: 5984
  type: LoadBalancer
