apiVersion: v1
kind: ReplicationController
metadata:
  name: question-service
spec:
  replicas: 1
  selector:
    app: question-service
  template:
    metadata:
      labels:
        app: question-service
    spec:
      containers:
      - name: question-service
        image: arsnovacloud/question-service:v0.1
        # Pull image from THM GitLab Container Registry (git.thm.de)
        # image: registry.thm.de/arsnovacloud/question-service:v0.1
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8080
        env:
        - name: TOMCAT_MAJOR_VERSION
          value: 8
        - name: TOMCAT_MINOR_VERSION
          value: 8.0.11
        - name: CATALINA_HOME
          value: /tomcat
