apiVersion: v1
kind: ReplicationController
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: arsnovacloud/user-service:latest
        # Pull image from THM GitLab Container Registry (git.thm.de)
        # image: registry.thm.de/arsnovacloud/user-service:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8080
