apiVersion: v1
kind: Service
metadata:
  name: user-service-db
  labels:
    app: user-service-db
spec:
  selector:
    app: user-service-db
  ports:
  - protocol: "TCP"
    port: 9005
    targetPort: 3306
  type: LoadBalancer
