apiVersion: v1
kind: Service
metadata:
  name: response-service
  labels:
    app: response-service
spec:
  selector:
    app: response-service
  ports:
  - protocol: "TCP"
    port: 9002
    targetPort: 8080
  type: LoadBalancer
