apiVersion: v1
kind: Service
metadata:
  name: question-service
  labels:
    app: question-service
spec:
  selector:
    app: question-service
  ports:
  - protocol: "TCP"
    port: 9000
    targetPort: 8080
  type: LoadBalancer
