apiVersion: v1
kind: Service
metadata:
  name: response-service-db
  labels:
    app: response-service-db
spec:
  selector:
    app: response-service-db
  ports:
  - protocol: "TCP"
    port: 9003
    targetPort: 5984
  type: LoadBalancer
