apiVersion: v1
kind: Service
metadata:
  name: socket-service
  labels:
    app: socket-service
spec:
  selector:
    app: socket-service
  ports:
  - protocol: "TCP"
    port: 9006
    targetPort: 3000
  type: LoadBalancer
